### ISSUE TITLE
Which request payload formats are accepted?

### ISSUE THREAD

**Issue by joostfarla** [open-education-api/specification#1]
In the current v1.0 spec document, there is no info regarding the media type (format) of the payload for POST/PUT calls. This should be added to the spec & docs.

We have 2 options here:

**application/x-www-form-urlencoded**

Similar to the format of HTTP query parameters but as a payload. For example, `foo=1&bar=value`

This is the default content type for HTML forms submitted by web browsers. Please note that an HTML form will typically not post directly to the API. Normally this is handled by a client (Javascript) or server application.

Cons:
- Limited support for nested fields. You have to do tricks with arrays or comma-separated values.
- There are multiple ways (workarounds) to send these kinds of complex structures. This has to be defined & documented properly, which makes it more complex for the developer.

**application/json**

Pros:
- Support for complex structures (nesting, arrays, etc)
- Easier to work with:
  - Native support in Javascript (JSON stands for JavaScript Object Notation) and other development platforms
  - You can send the current JSON representation directly without converting it to some other media type
- JSON supports (basic) data types: strings, numbers, booleans, null values etc
- Easy to validate against JSON schema (which is the way parameters are defined in the OpenAPI spec)

It is possible to support both, but I would suggest to pick one. 

My personal vote goes to _application/json_.

**Comment by fransward** [comment]
I vote for the JSON (application/json) media format as well.

**Comment by phavekes** [comment]
I vote for the JSON (application/json) media format as well.

**Comment by pgh70** [comment]
Why not also: application/xml ?

**Comment by joostfarla** [comment]
@pgh70 when you're serving both JSON and XML responses, I agree it makes sense to allow them both as input format. As long as you're not mixing form-data with JSON/XML media types, that should be perfectly fine!

**Comment by joostfarla** [comment]
This was already fixed for v1 (JSON only). Closing this issue since we have removed all writeable operations for v2.
