### ISSUE TITLE
Add POST to Person and Association

### ISSUE THREAD

**Issue by hamrt** [open-education-api/specification#100]
- [x] person POST

- [x] association POST

**Comment by hamrt** [comment]
Do we want other return information besides OK (e.g. for person do we want the return value of the created UUID for the person in the new system? This could lead to tracking questions)
Do we want to always provide all information? For association the proper keys of person en offering and role should suffice (this is implementend for now through the form sollution.

**Comment by jelmerderonde** [comment]
During the work group meeting on November 12 we concluded that now is not the right time to implement POSTs. We will revisit this when we look closer at server-to-server interactions.

**Comment by hamrt** [comment]
POST is added into 4.1 specification as a proposal still waiting. Is a more specific version of issue #26 . Discussion needed on transaction mechanism for POST will this be done only for m2m or also in user flow.

**Comment by jelmerderonde** [comment]
@hamrt can create a PR against 4.1 branch with these 2 posts

**Comment by hamrt** [comment]
should be fixed in Post person associations #170

**Comment by jelmerderonde** [comment]
Closed by #175
