### ISSUE TITLE
OOAPI and RIO compatibility

### ISSUE THREAD

**Issue by hamrt** [open-education-api/specification#106]
In trying to make the education domain compatible these two specifications need alignment.

Checklist:
- [x] STAP aanbod moet via OOAPI v5 gecommuniceerd kunnen worden
- [x] NLQF voor particulier onderwijs wordt anders bepaakd dan voor niet particulier onderwijs
- [x] #196
- [x] program -> collection

**Comment by hamrt** [comment]
Need more information.

1. On distinction between object types. RIO supports three types of programs
Program (descriptive) (Program as an Intended Learning Outcome ILO)
Program (linked to a location and at a time) (Program as a Teaching and Learning Activity TLA)
Program that is acutally taught (programOffering)
2. Attributes need to be added
3. Enumerations need to be aligned

Perphaps split this issue into separate issues for manageability

1.

**Comment by jelmerderonde** [comment]
Discussiepunt: nog even goed nadenken over de historie-functionaliteit van RIO (perioden) en wat we daar wel of niet voor moeten ondersteunen.

Concreet voorbeeld: hoe gaat het werken als een instelling bijv. per 1 sept een naamswijziging wil doorvoeren op een AangebodenOpleiding.

**Comment by jelmerderonde** [comment]
@ruttromp Op het [Miro bord](https://miro.com/app/board/o9J_kkIo8Qk=/?moveToWidget=3458764520109690014&cot=14) zijn twee scenario's toegevoegd die we vrijdag kunnen bespreken.

**Comment by jelmerderonde** [comment]
Voor degene die dit ticket uiteindelijk verder uitwerkt: het lijkt noodzakelijk (vanwege eenmalige harmonisatie) om in een eventueel `collab` object of elders in onderwijsaanbod-objecten ook de RIO-codes op nemen.

**Comment by jelmerderonde** [comment]
@hamrt wat denk je van de naam `consumer` ipv `collab`?
