### ISSUE TITLE
Multi-lingual support

### ISSUE THREAD

**Issue by hamrt** [open-education-api/specification#107]
OOAPI also needs support for dutch and English descriptions and naming of certain endpoints (perhaps even German)

**Comment by jelmerderonde** [comment]
I think it was decided we should use Content negotiation for this: https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation

OAS provides a mechanism to describe the headers we support for this scenario: https://swagger.io/docs/specification/describing-parameters/#header-parameters

We should add these to the spec
