### ISSUE TITLE
OOAPI V4: "Toetsvorm" is a missing attribute of Component in case of a Test

### ISSUE THREAD

**Issue by JanHendrikvanSchaik** [open-education-api/specification#110]
We discovered that we cannot interface the form of a test with a formal attribute.
Examples of testforms are "written", "assesment", "digital", etc.
Depending on the testfrom of a test, the right facilities are planned and rostered in our application.
For an assesment, a small room is appropiate, a digital test requires a room with computers.

We will use the EXT object in the meantime.

Please add a TESTFORM attribute with OOAPI V4.1

**Comment by jelmerderonde** [comment]
Might also be possible to increase the enumeration list `type`. Or add an attribute `subtype`.

**Comment by mpdejong** [comment]
This requirement could be met by adding an additional attribute named 'modeOfDelivery' like the one available at /Course.

**Comment by jelmerderonde** [comment]
@JanHendrikvanSchaik could you take a look at Rugter's question?

**Comment by JanHendrikvanSchaik** [comment]
At the moment I'm discussing the possible values for this enum with Saxion.
We will come back with a proposal.

**Comment by JanHendrikvanSchaik** [comment]
We have the next proposal for this enum:
BP; Beroepsproduct
PJ; Project
VA; Vaardigheden/Skills
VP; Verplichting/Obligation
N; Niet van toepassing/ Not applicable
AS; Assesment
PF; Portfolio
S; Schriftelijk/Written
D; Digitaal/Digital
W; Werkstuk/Report
PR; Presentatie/Presentation
M; Mondeling/Oral

**Comment by jelmerderonde** [comment]
Tijdens de technische sessie 28 sept 2023 bepaald dat we dit in v4 of v5 niet willen toevoegen. Als "toetsvorm" nodig is, kan voor een dergelijk attribuut in v4 en v5 een extension binnen de entiteit Component gebruikt worden. 

Voor een versie 6 lijkt het verstandiger om het model uit te breiden met 1 of meer nieuwe entiteiten (tests / assessement / testofferings, of iets dergelijks)
