### ISSUE TITLE
OOAPIv4: missing attribute Duration for Component

### ISSUE THREAD

**Issue by JanHendrikvanSchaik** [open-education-api/specification#111]
We discovered that we cannot interface the duration of a test with a formal attribute.
Mostly the duration of a test are specified in minutes.

We will use the EXT object in the meantime.

Please add a Duration attribute with OOAPI V4.1

**Comment by jelmerderonde** [comment]
Also see #154

**Comment by hamrt** [comment]
Closed by PR #189
