### ISSUE TITLE
incorrect value of the query parameter 'role' in offerings/{ID}/associations and persons/{ID}/associations

### ISSUE THREAD

**Issue by hermanvand** [open-education-api/specification#119]
The query parameter 'role' in offerings/{ID}/associations and persons/{ID}/associations describes one of the values as 'student assistant'. This should be 'teaching assistant' as described in the association object that is the result of these requests.

**Comment by jelmerderonde** [comment]
Maybe fixed by #101. Double check once that PR is merged

**Comment by jelmerderonde** [comment]
Fixed by #101
