### ISSUE TITLE
Do we need to keep supporting XML?

### ISSUE THREAD

**Issue by joostfarla** [open-education-api/specification#12]
The current de-facto standard when it comes to request/response formats of web API's is JSON. Do we need to keep supporting XML? If yes, we need to specify how XML-specific elements are named (list elements, element attributes etc...) and probably provide an XSD.

**Comment by usapieter** [comment]
From our perspective - we have been offering an XML option in every API we have been providing, but no customer is actively using it. 

I would agree that the de-facto standard is JSON, so i would not see any reason to support XML.

**Comment by tomkuipers** [comment]
I agree JSON is the de-facto standard and will probably cover the needs from developers. However if we do want to provide XML, we should also provide an XSD.
+1 for only JSON

**Comment by phavekes** [comment]
+1 for json

**Comment by pgh70** [comment]
I don't think xml should be part of the specification.. Of course is everyone free to also support the results in xml (or html, cvs, yaml, ....)... some API-frameworks even give this functionality 'for free'.
Making it part of the specification makes it more difficult to meet the specification.
So +1 for json only (which simplifies the specification a bit)

**Comment by fransward** [comment]
+1 for JSON and JSON only.

**Comment by joostveerman** [comment]
The HU only supports json in our implementation so +1 for JSON only.

**Comment by joostfarla** [comment]
XML support has been dropped in the v2 branch.
