### ISSUE TITLE
Discussion: should we consider other types of identifiers for future versions of the OOAPI?

### ISSUE THREAD

**Issue by jelmerderonde** [open-education-api/specification#124]
A discussion @arthurvanalten, @hermanvand and I had during a hackathon where OOAPI was discussed led to the creation of this issue.

In the discussion we were wondering whether more "meaningful" identifiers (that maybe also act as addresses) might be worthwhile to consider.

**Comment by jelmerderonde** [comment]
Iets meer toelichting: over het algemeen wordt aangeraden om in REST API's gebruik te maken van betekenisloze identifiers om resources uniek te identificeren. Dit is ook de reden dat de OOAPI UUID's gebruikt als resources identifiers.

Toch vraag ik me soms af of het, in de context van het hoger onderwijs, niet handiger zou zijn om voor identifiers te kiezen die meer betekenis met zich meenemen en eventueel zelfs "resolvable" kunnen zijn. Denk aan iets als een urn:
`urn:x-surf:uu.nl:course:<een identifier van een cursus bij de UU>`

Dit zou een aantal voordelen hebben:
- Als de identifier goed vormgegeven is, kunnen we collisions tussen instellingen gegarandeerd voorkomen, en toch resources instelingsoverstijgend combineren in lijsten.
- Middleware zoals de OOAPI gateway kan makkelijker aggregeren en aan een request voor een individuele resource zien welke instelling benaderd moet worden voor meer informatie.

Ook in breder Europees verband wordt hierover nagedacht, zie bijv.: https://heidirepo.github.io/HEIDI/#identifiers

Desalniettemin raadt iedere handreiking die je leest over API's aan om voor betekenisloze identifiers te kiezen. Ik ben dus erg benieuwd naar wat mogelijke tegenargumenten zouden kunnen zijn.

**Comment by thepercival** [comment]
Identifiers worden gebruikt voor het identificeren van het object waarin de identiteit zich bevindt en zijn uniek. Voor de functionaliteiten die je wilt bieden (wat je beschrijft onder "voordelen") "misbruik"  je nu de identifier. Waarschijnlijk is dit omdat het een makkelijke oplossing lijkt/is of omdat er nu geen andere technische oplossing mogelijk is.

**Comment by jelmerderonde** [comment]
IMS maakt bijvoorbeeld gebruik van een sourceId.

**Comment by sanderbrinkhuis** [comment]
UUID -> 2 oplossingsrichtingen indien backend applicatie deze niet standaard heeft:
- applicatie tabellen aanpassen en uuid toevoegen (niet altijd mogelijk\wenselijk) bij een standaard pakket)
- vertaaltabel implementeren (sourceid <-> uuid) op een andere plek

**Comment by jelmerderonde** [comment]
Naar aanleiding van de discussie in de OOAPI werkgroep link ik hier ook nog even naar het relevante deel van de API strategie van de overheid: https://docs.geostandaarden.nl/api/vv-hr-API-Strategie-ext-20190715/#openbare-identifiers

Al blijken we daar alweer op achter te lopen:

>

    UUID

    Het wordt aanbevolen om voor resources die een vertrouwelijk karakter hebben het concept van een UUID (Universally-Unique IDentifier) te gebruiken. Dit is een 16-bytes (128-bits) binaire representatie, weergegeven als een reeks van 32 hexadecimale cijfers, in vijf groepen gescheiden door koppeltekens en in totaal 36 tekens (32 alfanumerieke tekens plus vier afbreekstreepjes):

    550e8400-e29b-41d4-a716-446655440000

    Om te zorgen dat de UUID's korter en gegarandeerd "web-veilig" zijn, is het advies om alleen de base64-gecodeerde variant van 22 tekens te gebruiken. De bovenstaande UUID ziet er dan als volgt uit:

    abcdEFh4520juieUKHWgJQ

**Comment by jelmerderonde** [comment]
Closed this, see #142
