### ISSUE TITLE
Discussion: should we also add an 'ext' attribute to lists of items like /programs and /courses

### ISSUE THREAD

**Issue by hermanvand** [open-education-api/specification#128]
currently the ext attribute can be added to single items like /programs/{ID} and /courses/{ID}

**Comment by hermanvand** [comment]
This ext can be used to supply information about the total number of items. For example:

```
   "ext": {
                "totalItems": 10383,
                "totalPages": 1039
            }
```

**Comment by fransward** [comment]
No objection to extend this like suggested.

**Comment by jelmerderonde** [comment]
Vervangen door #140
