### ISSUE TITLE
urlendpoint persons should be people

### ISSUE THREAD

**Issue by cdunnink** [open-education-api/specification#134]
Hallo,

"personen"  should be translated "people" not "persons".
Maybe something for version 5. It is quiet breaking.
For automatic urlendpoints-generators (translation of the model) this is a problem.

**Comment by jelmerderonde** [comment]
@cdunnink could you take a look at Rutger's question?

**Comment by thepercival** [comment]
1: it is of course not really a problem. Better semantics will lead to better usability.
2: no new possibilities will arise, imo

**Comment by mpdejong** [comment]
Looking at the IMSGlobal Edu-API endpoint and description, we could stay with 'persons'.

From the Edu-API v1.0 Base Document:
/persons         | GET | Read all persons for an institution
/persons/{Id}   | GET | Read person with a specific Id
