### ISSUE TITLE
is studentgroup the vocational-education-equivalent  of a "course" or an "offering"?

### ISSUE THREAD

**Issue by cdunnink** [open-education-api/specification#135]
From the vocational education point-of-view we have no courses(maybe "keuzedelen"), but rather work with "studentgroups".
A "studentgroup" represents a group of persons who are following a "program" for a certain learning year.
It is also possible that students from the same "studentgroup" are following different "programs". All the lessons are given to one or more "studentgroups". Could anyone map this to a valid openapi-mapping?
IMO the "studentgroup" could be seen as a planning-entity. The problem is that we do not know which "components" or "programs" are attached to the "studentgroup". This could be important when we want to know the results for a certain offering.

**Comment by jelmerderonde** [comment]
Wordt meegenomen in de uitwerking van #47.

Let op:
> A "studentgroup" represents a group of persons who are following a "program" for a certain learning year."
