### ISSUE TITLE
How to return 'personal' results of an OAuth authenticated user

### ISSUE THREAD

**Issue by usapieter** [open-education-api/specification#14]
In the last workgroup meeting, it was mentioned there should be a way "/me" way of retrieving personalized data. 

I've checked the documentation for 1.0 again - and could not find any description of it.

In the case of (For example) courseresults, as user has an OAuth token, and the ID in the OAuth token is used to get the courseresults for that specific user.

How would we implement this into the standard?

**Comment by pgh70** [comment]
I see two possible approaches:

1. The VOOT (http://openvoot.org) way:
use specific endpoints for it:
GET /me/courseresults
GET /me/courseresults/{courseId}
GET /me/testresults
GET /me/testresults/{testId}

2. Allow the use of the string 'me' on every place a userId is a parameter (the google way):
GET /courseresults/me
GET /courseresults/me/{courseId}
GET /testresults/me
GET /testresults/me/{testId}

My vote goes to approach 2... No need for extra endpoints, only add comment in the spec: 'use me for the (OAuth2) authenticated user' for the userId fields.

**Comment by usapieter** [comment]
Approach 2 would work just fine! 👍

**Comment by joostfarla** [comment]
Option 2 is perfect, but I think we should prefix it (for example `@me`) to prevent naming conflicts.

**Comment by pgh70** [comment]
If a recall correctly for instance google (and OpenSocial) used @me before, but switched to me... Looking at some major API's (google, facebook, ...) the two approaches seems te be te currently used ones...

**Comment by usapieter** [comment]
I have no preference as to use /@me or /me - I don't think the /me would result in any naming conflicts, so that would work just fine.

**Comment by joostveerman** [comment]
I support this initiative because we workt too with OAuth token with a user identifier. So to put the user ID in the URL is not nessescary. I'm not into detail at the moment whether it should be @me or me. The argument for the endpoint I understand so I suggest too option 2.

**Comment by usapieter** [comment]
for our current implementation at Leiden we have chosen to go with /me
