### ISSUE TITLE
[Change request]: should we also add an 'ext' object to lists of items like /programs and /courses

### ISSUE THREAD

**Issue by hermanvand** [open-education-api/specification#140]
### Organization

SURF

### Project

OOAPI v4 stimuleringsregeling

### Contact Details

herman.vandompseler@surf.nl

### Short description

currently the ext object can be added to single items like /programs/{ID} and /courses/{ID}

But this feature is also requested for lists like /programs & /courses

this is a new version of #128 to test the issue template

### Version

v4

### Usecase

This ext can be used to supply information about the total number of items. For example:

`
   "ext": {
                "totalItems": 3076,
                "totalPages": 308
            }
`

### Which institutions support this change?

InHolland University of Applied Sciences (Arthur van Alten), Leiden University of Applied Sciences (Mark de Jong, Frank Schimmel)

### Proposed solution

add ext{} object to lists

### Requests and responses

the responses to these calls will change

/academic-sessions
/buildings
/courses
/news-feeds
/organizations
/persons
/programs
/rooms

**Comment by jelmerderonde** [comment]
Vorig WG overleg is al besloten dit op te pakken. Dit issue vervangt #128. close #128. Herman werkt dit uit in een PR.

**Comment by hermanvand** [comment]
is #182
