### ISSUE TITLE
Versoepelen richtlijn mbt UUID specificatie

### ISSUE THREAD

**Issue by maartenvanschie** [open-education-api/specification#142]
### Organization

OOAPI Werkgroep / Universiteit Leiden

### Project

Pilot Studentmobiliteit / LDE samenwerking

### Contact Details

maartenvanschie@gmail.com

### Short description

OOAPi V4 vereist het gebruik van de UUID voor het uniek en globaal identificeren van gegevensobjecten zoals courses and offerings. 

Nu is het zo dat het SIS voor deze objecten al een unieke identifier heeft binnen de scope van het SIS (vanaf nu SIS-ID genoemd). Deze identifier voldoet niet aan de UUID specificatie.

Voor leveren van gegevensobjecten via een OOAPI endpoint met een UUID die herleidbaar blijf naar het gegevensobject in het SIS zijn 2 mogelijke oplossingsrichtingen:
1. In het SIS wordt voor elke object een UUID gegeneerd en gerelateerd aan de SIS-ID, de lijst met relaties SIS-ID - UUID wordt beheerd in het SIS.
2. In een extern systeem ( bv Servicebus) wordt de UUID gegeneerd en gerelateerd aan de SIS-ID de lijst met relaties SID-ID - UUID wordt beheerd in het externe systeem.

Probleem, voor in ieder geval Universteit Leiden, is dat het mplementeren hievan nu niet haalbaar is, omdat deze opties te kostbaar zijn om te implementeren kwa (doorloop)tijd en geld.

Echter als er voor een periode toegestaan wordt om de specificatie van de UUID te versoepelen, en toe te staan dat er betekenis in de UUID mag worden toegevoegd dan zou implementatie van de OOAPI v4 wel haalbaar zijn.

Het voorstel is om voor de duur van 3 jaar, toe te staan dat de UUID zo wordt genereerd dat deze syntaxtisch voldoet aan de UUID , maar dat onderdeel van de UUID te herleiden is naar de SIS-ID. 
De instellingspecifieke gegevenstransformatie tussen SIS en OOAPI afnemer kan dan met een business logica de SID-ID vertalen naar een UUID en als de UUID weer terugkomt dan kan de business logica vanuit de UUID weer SIS-ID afleiden. Hiermee hoeft er geen wijziging in het SIS plaats te vinden en hoeft er ook geen opslag van de relatie SIS-ID UUID plaats te vinden.

Risico's  

Risico: Externe systemen kunnen gaan, bouwen op de SIS-ID, waarmee ongewenste afhankelijkheid geintroduceerd.
Maatregel: Externe systemen mogen geen gebruik maken van de SIS-ID.
Riscowaardering: laag

Risico: Externe systemen krijgen meer informatie van het SIS dan nodig wat misbruik in de hand werkt
Maatregel: Businesslogica past een cryptografische methode bij de transformatie tussen UUID en SIS-ID
Risicowaardering: laag

### Version

v4

### Usecase

LDE pilot studentmobiliteit

### Which institutions support this change?

Leiden University (Maarten van Schie)

### Proposed solution

Versoepelen UUID eisen mbt systeemagnostisch genereren

**Comment by jelmerderonde** [comment]
Tijdens WG 16 sep 2021 besproken dat de gewenste oplossing is om in de documentatie op te nemen dat UUID's v4 de voorkeur genieten, maar dat v3 of v5 UUID's ook toegestaan zijn. Dit zou het probleem van Universiteit Leiden ook oplossen.

@maartenvanschie maakt een PR om dit in de spec/documentatie op te nemen.

**Comment by jelmerderonde** [comment]
Dit issue is ook van belang met het oog op de voorziene RIO koppeling. Er is een wens vanuit DUO om de `eigenSleutel` een UUID te laten zijn.

**Comment by jelmerderonde** [comment]
@ruttromp Ewout en ik concluderen dat het het beste is om in de standaard gewoon UUID's aan te houden. Je kunt informeel wel met een instelling afspreken dat ze niet "echt random" UUID's gebruiken, maar dat ze een soort nep-UUID's hanteren als ze er anders echt niet uitkomen, maar dat zouden we wel willen afraden.

**Comment by jelmerderonde** [comment]
We've decided to close this issue, since UUIDs still remain the best solution we know of.
