### ISSUE TITLE
[Change request]: Improve error responses for all requests

### ISSUE THREAD

**Issue by jelmerderonde** [open-education-api/specification#144]
### Organization

SURF

### Project

Studentmobiliteit

### Short description

Right now all requests feature at least a 200 response and 404 responses should be defined for requests that return a single entity.

Some improvements should be made to improve the description of error responses.

**Make 404's consistent**
- Some requests for lists of entities also allow a 404 response, which is not logical. If no items are found a 200 should be returned with an empty list. See for example `GET /courses/{courseId}/offerings`

**Add missing status codes**
- It seems logical to add at least 400 (Bad Request) as a status code we describe.
- Maybe also 500 (Internal Server Error), 501 (Not Implemented) and 502 (Bad Gateway)?
- Which status codes are meaningful to explicitly describe for the OOAPI? An argument can be made for many of the valid status codes, but we don't want to add them all. This warrants a discussion I guess.

See also #125 

### Version

v4

### Usecase

This would make it possible to handle error codes in a consistent matter across different implementations, making it easier for clients (or other intermediary systems) to communicate about errors to their users.

### Proposed solution

- Fix the existing inconsistencies: 404's can only be returned when asking for a specific, singular, resource.
- Decide on which other status codes we want to describe and add them to all relevant requests.

### Requests and responses

Potentially all requests

**Comment by jelmerderonde** [comment]
Comparing the current response codes / errors to the eduapi draft specification has resulted in the following response codes that we probably want to describe:

**For requests returning arrays of objects:**
| Code | Description                         |
|------|-------------------------------------|
| 200  | Succes                              |
| 400  | Invalid request                     |
| 403  | Forbidden / authorization incorrect |
| 405  | Method not implemented              |
| 429  | Too many requests                   |
| 500  | Fatal error                         |

Note: the eduapi spec also suggests using a 204 response when returning an array with zero object. According to the [HTTP spec](https://httpwg.org/specs/rfc7231.html#status.204) this seems incorrect: 

> A 204 response is terminated by the first empty line after the header fields because it cannot contain a message body.

So I am ommitting 204 as a response code here.

**For requests returning a single object:**
| Code | Description                         |
|------|-------------------------------------|
| 200  | Succes                              |
| 400  | Invalid request                     |
| 403  | Forbidden / authorization incorrect |
| 404  | Not found                           |
| 405  | Method not implemented              |
| 429  | Too many requests                   |
| 500  | Fatal error                         |

**Comment by jelmerderonde** [comment]
@ruttromp ik denk dat ik hier wel een PR van kan maken, hier hoeven we denk ik niet veel discussie over te voeren toch?

**Comment by ruttromp** [comment]
@jelmerderonde mee eens, in de werkgroep was hier vorig jaar al overeenstemming over

**Comment by jelmerderonde** [comment]
Closed by #174
