### ISSUE TITLE
[Change request]: Make brin conditionally required for root and branch organizations

### ISSUE THREAD

**Issue by jelmerderonde** [open-education-api/specification#146]
### Organization

SURF

### Project

Kies op Maat

### Short description

If an organization is of type `root` or of type `branch` (see issue #145) it should have a `brin`-identifier. All Dutch educational institutions and their different branches have such a number.

### Version

v4

### Usecase

I'm not entirely sure what the specific usecase is: I will look into this.

### Proposed solution

Make `brin` conditionally required if organization type = `root` or `branch`.

### Requests and responses

- `GET /organizations/{organizationId}`
- `GET /organzations`

And all requests that allow expands on organization.

**Comment by ruttromp** [comment]
Ik stel voor om dit verzoek te sluiten omdat:
- brin code niet verplicht kan worden vanwege implementaties OOAPI buiten Nederland
- OpenAPI 3.0 kent oneOf/anyOf logica, maar geen goede oplossing voor conditionally required attributes

**Comment by jelmerderonde** [comment]
@ruttromp ik snap je denkwijze, ik zoek nog wel naar een oplossing hoe een brincode wel teogevoegd kan worden aan een organisatie-onderdeel als een organisatieonderdeel dat wel heeft en de afnemer behoefte heeft aan die code. Mogelijk in een `collab` object?

**Comment by ruttromp** [comment]
Besproken met KOM ontwikkelaar (Roland). De huidige mogelijkheid om de BRIN code uit te lezen via `GET /organizations` volstaat. Zowel voor de instelling als de vestigingen.
