### ISSUE TITLE
How to display use of caching mechanism in response output?

### ISSUE THREAD

**Issue by usapieter** [open-education-api/specification#15]
For some API's we are providing a caching mechanism in order to improve performance.

How do we relay the fact that a response is cached, and what TTL is used?

For now, we have chosen to relay to information in the response header:

examples:

Cache-Control: max-age=60
Cache-Control: no cache

**Comment by joostfarla** [comment]
Caching is certainly a good thing! However, I'm not sure whether this should be defined in the standard spec. Every service provider is free to implement parts of HTTP or not (like HTTP caching). It's just about conforming to the HTTP spec. Nothing would break if one service provider is not offering support for caching, right?

**Comment by tomkuipers** [comment]
Sticking to cache information in the response header is enough. I would not include it in the specification

**Comment by joostveerman** [comment]
I should suggest this as optional fields in the header.

**Comment by joostfarla** [comment]
We agreed this should not be part of the general spec. We could add a rule about conforming to the HTTP 1.1 spec in the compliance document though.
