### ISSUE TITLE
All time attributes

### ISSUE THREAD

**Issue by jelmerderonde** [open-education-api/specification#154]
### Short description

The last year or so I have received many requests to add various attributes to the OOAPI related to time. I've created this issue to track all the attributes, so we can consider these changes as a whole.

### Version

v5

### Usecase

Various usecases related to correctly describing educations and educationOfferings to systems and prospective students.

Compatibility with RIO also requires that we add some attributes related to time.

### Proposed solution
| Object | Attribuut | Type | Verplicht? | Aanbeveling | Opmerkingen | Mapt naar RIO object(s) | RIO attribuut | Type | Verplicht? | RIO omschrijving |
|---|---|---|---|---|---|---|---|---|---|---|
| Program | ~~lengthOfProgram~~ | integer | nee | Vervangen door duration attribuut |  |  |  |  |  |  |
| Education | duration | string <duration> | nee | Toevoegen aan v5 | Formaat zoals gedefinieerd in   OpenApi 3.1, duration, RFC3339, mapt naar afwijkendeOpleidingsduurOmvang, in   combinatie met afweijkendeOpleidingsduurEenheid | AangebodenHoOpleiding | afwijkendeOpleidingsduurOmvang | N(..) | nee | De lengte in tijd van een studie uitgedrukt in studieduur   eenheden. |
| Education | firstStartDate | string <date> | nee | Toevoegen aan v5 |  | AangebodenHoOpleiding | eerstelnstroomdatum | AN(..) | nee | Moment waarop voor het eerst deelnemers de betreffende opleiding kunnen   volgen. |
| Offering | startDate | string <date> | **ja** | Niet verplichten? |  | AangebodenHoOpleidingCohort | instroommoment |  | nee | De dag waarop het cohort voor de aangeboden opleiding begint. |
| Offering | endDate | string <date> | **ja** | Niet verplichten? |  | AangebodenHoOpleidingCohort | einddatum |  | nee | De datum die het einde van de periode aangeeft (exclusief). De einddatum   van deze variant van de opleiding. De begindatum van deze variant is het   instroommoment of de begininstroomperiode/eindeinstroomperiode. |
| Offering | enrollStartDate | string <date> | nee | Toevoegen aan v5 | We gebruiken dit attribuut al in de Pilot Studenmobiliteit | AangebodenHoOpleidingCohort | beginAanmeldperiode | AN(..) | ja | Is de eerste dag waarop een aspirant-student zich aan kan melden voor het   betreffende cohort van een aangeboden opleiding. |
| Offering | enrollEndDate | string <date> | nee | Toevoegen aan v5 | We gebruiken dit attribuut al in de Pilot Studenmobiliteit | AangebodenHoOpleidingCohort | eindeAanmeldperiode |  | nee | Is de laatste dag waarop een aspirant-student zich aan kan melden voor   het betreffende cohort van een aangeboden opleiding. |
| Offering | flexibleStartDate | string <date> | nee | Overweeg toe te voegen aan v5 of "collab" object |  | AangebodenHoOpleidingCohort | beginInstroomperiode | AN(..) | nee | De eerste dag dat een student in een cohort van een aangebodenopleiding   met een flexibele instroom kan beginnen. Studenten kunnen ook later beginnen.   De opleiding start op het moment dat de leerling begint en deze mist daardoor   niets van de opleiding. |
| Offering | flexibleEndDate | string <date> | nee | Overweeg toe te voegen aan v5 of "collab" object |  | AangebodenHoOpleidingCohort | eindelnstroomperiode |  | nee | De laatste dag dat een student kan beginnen in een cohort van een   aangeboden opleiding met een flexibele instroom. Studenten kunnen niet later   dan deze datum aan dit cohort van deze aangeboden opleiding beginnen. |
|  |  |  |  | Voorlopig niet opnemen als attribuut in v5 |  | HoOpleiding and AangebodenHoOpleiding | begindatun | AN(..) DatumType | yes | De datum die het begin van de   periode aangeeft (inclusief). |
|  |  |  |  | Voorlopig niet opnemen als attribuut in v5 |  | HoOpleiding and AangebodenHoOpleiding | einddatum | AN(..) DatumType | no | De datum die het einde van de   periode aangeeft (exclusief). |
|  |  |  |  | Voorlopig niet opnemen als attribuut in v5 |  | HoOpleidingPeriode and AangebodenHoOpleidingPeriode | begindatum | PeriodeBeginDatum | yes | De datum die het begin van de   periode aangeeft (inclusief). |
|  |  |  |  | Voorlopig niet opnemen als attribuut in v5 |  | HoOpleidingPeriode and AangebodenHoOpleidingPeriode | einddatum | PeriodeEindDatum | no | De datum die het einde van de   periode aangeeft (exclusief). |
|  | contactHours |  |  | Voorlopig niet opnemen als attribuut in v5 |  |  |  |  |  |  |
|  | workload |  |  | Voorlopig niet opnemen als attribuut in v5 |  |  |  |  |  |  |

[allthingstime.xlsx](https://github.com/open-education-api/specification/files/8214700/allthingstime.xlsx)

**Comment by jelmerderonde** [comment]
@ruttromp ik heb aan dit issue een voorstel toegevoegd dat we kunnen bespreken.

**Comment by jelmerderonde** [comment]
Wel goed om ons te realiseren dat veel van de velden in RIO alleen dates zijn (zonder timestamp en/of tijdzone). Dus bij de translatie naar RIO moeten we eea nog wel omzetten. Ook moeten we ons afvragen welke van de nieuw toe te voegen attributen aan de OOAPI v5 date of datetimes moeten worden.

**Comment by ruttromp** [comment]
@jelmerderonde het lijkt mij prima om hiervoor al een PR te maken. In EduAPI wordt zowel date als date-time gebruikt, bijvoorbeeld `EducationOffering`-`startDate` is een date en `EducationOffering` - `dateLastModified` een date-time.

**Comment by jelmerderonde** [comment]
Prima, goede klus voor vanmiddag
