### ISSUE TITLE
[Change request]: Consider removing the profileOfProgram attribute

### ISSUE THREAD

**Issue by jelmerderonde** [open-education-api/specification#156]
### Organization

SURF

### Short description

The `profileOfProgram` attribute of the Program object describes the same information as the description.

We should consider dropping this attribute to be more clear.

### Version

v4

### Proposed solution

Drop the attribute.

**Comment by ruttromp** [comment]
@mpdejong as discussed Feb 11, an additional check is needed to see if this change conflicts with Edu-API

**Comment by hermanvand** [comment]
i might have a use case for this attribute. In describing a minor (is a type of program) for a cataloq we plan to use description as 'an introduction to the minor' and profileOfProgram as 'an in depth description of the content/modules/courses/topics of the minor'. 

the difference we would like to see between the two attributes is a high level description (promotional) vs. a more detailed description (content).

**Comment by Marcel-Noordzij** [comment]
Dont’ we have the program -> course relation to define the courses of a program (minor).

Since the description of a program already will be used to contain multiple subjects (titles), it could also be used to define a textual description of the courses if needed as just another subject in the provided text. Just like entry requirements, study organization, etc.

**Comment by jelmerderonde** [comment]
@hermanvand ik kan me wel vinden in de opmerking van @Marcel-Noordzij. Is `profileOfProgram` echt nodig? Kan de informatie die je beschrijft niet gewoon in een langere `description`? Of inderdaad door te verwijzen naar onderliggende courses?

**Comment by hermanvand** [comment]
Klopt, we kunnen de course informatie ook ergens anders kwijt. Daarvoor hoeven we hem misschien niet te handhaven. 

Dit veld komt overigens uit de ects course catalogue. Toen v4 werd opgebouwd hebben we geprobeerd daarop zoveel mogelijk aan te sluiten. In dat kader vind ik dit attribuut ook nog wel zinvol. Maar dat kan ook bij de 'description' vermeld worden.

**Comment by jelmerderonde** [comment]
Closed by #184
