### ISSUE TITLE
[Change request]: Consider adding ISAT code to programs

### ISSUE THREAD

**Issue by jelmerderonde** [open-education-api/specification#157]
### Organization

SURF

### Short description

Consider adding an ISAT code attribute to programs.

### Version

v4

**Comment by ruttromp** [comment]
@jelmerderonde of @hermanvand is er een use case bekend voor het toevoegen van ISAT code aan Programs?

**Comment by jelmerderonde** [comment]
@ruttromp volgens mij was dit een wens vanuit Kies Op Maat. De ISAT code zegt iets over de erkenning van het programma geloof ik, maar @hamrt weet dat beter.

Bij nader inzien is de vraag of dit echt in v5 thuishoort of meer in het reguliere OOAPI proces besproken moet worden.

**Comment by hamrt** [comment]
kan zo maar is het niet handiger om er een echt object van te maken ipv het object telkens op te nemen al additional properties? een beejte analoog aan de manier waarop de language key value pairs opgelost moet worden

**Comment by jelmerderonde** [comment]
Fixed by #190
