### ISSUE TITLE
Add OOAPI profiles to the specification to get a better understanding of OOAPI use

### ISSUE THREAD

**Issue by hermanvand** [open-education-api/specification#159]
### Organization

SURF

### Project

SURFeduhub

### Contact Details

herman.vandompseler@surf.nl

### Short description

An OOAPI profile is a description of the use of OOAPI for a specific purpose. This description describes specific OOAPI user questions like:
- How can i use OOAPI to fill a course catalogue?
- Howto use OOAPI to make student rosters?

With OOAPI profiles we can:
- achieve a better understanding of the purpose of OOAPI
- inform users on the use of OOAPI for specific purposes
- do beter validation on endpoints

### Version

v5

### Usecase

Frontends that use OOAPI to fetch content can describe which OOAPI profiles they implemented. By implementing the same profile at an endpoint, the institution will know for sure that the data will be displayed correctly in the frontend.

Have a look at https://eduxchange.nl for example, they could say
- profile=coursecatalogue
- extension:targetGroup=[EWUU|LDE]

### Proposed solution

An OOAPI profile could be a yaml/json file with the following structure:

- Profile: "string" [“onderwijscatalogus” | ”rooster” | “…”]
- OOAPI Version:[v4|v4.1|v5]
- Endpoints
  - /organizations
  - /organizations/{ID}/courses
  - /courses
- Objects & Attributes
  - Organizations
    - Organization.name
    - Organization.logo
    - Motivation: This profile requires these organization attributes to show an organization page to the student
  - Courses
    - Course.name
    - Course.ects
    - Motivation: The courses are the most important elements of this profile and show the students the possible electives
- Relations
  - Organization/{ID}/courses -> courses.organization
  - Motivation: courses must be related to an organization to make sure that all relevant courses can be presented on the organization page
- Parameters 
  - Organization?type=root is mandatory to display a root organization
- Enumerations
  - "describe enumerations that are required"
- Extensions
  - Courses.ext.targetGroup is used to specify the elective courses to be shown

### Requests and responses

This change will not add any objects and/or attributes in de the OOAPI spec. It will describe a combination of existing objects/attributes to give meaning to a particular use of OOAPI.

**Comment by jelmerderonde** [comment]
Probably not part of the OOAPI spec itself, but something to take up somewhere else?

@hermanvand ok to close this here and take it up elsewhere?
