### ISSUE TITLE
[Change request]: voeg locatie-informatie toe aan alle offerings

### ISSUE THREAD

**Issue by jelmerderonde** [open-education-api/specification#164]
### Organization

SURF

### Project

Project Studentmobiliteit

### Short description

Het toevoegen van informatie over de locaties waar onderwijs gegeven wordt, zodat studenten zich beter kunnen oriënteren en een keuze kunnen maken.

### Version

v4

### Usecase

Bij het oriënteren op onderwijsaanbod is het voor studenten relevant om te weten waar het onderwijs gegeven zal worden. Studenten zijn daarbij vooral geïnteresseerd in welke stad/plaats het onderwijs zal zijn, zodat ze bij hun keuze rekening kunnen houden met reistijd e.d. Ook de "locatie" online kan natuurlijk een optie zijn.

Onderwijsaanbod (offerings), zeker programOfferings, kunnen op meerdere plaatsen aangeboden worden. Denk bijv. aan een minor of joint program waarbij onderwijs in een aantal steden (en online?!) plaatsvindt.

Door locaties toe te voegen aan alle offerings kan deze usecase bediend worden.

### Proposed solution

Bij de oplossing moeten we rekening houden met een aantal zaken:
- Een offering kan op meerdere locaties gegeven worden.
- Een componentOffering kent al het attribuut `room` waarmee ook verwezen wordt naar een locatie.
- De oplossing moet rekening houden met locaties die niet in Nederland zijn.
- Locaties zoals "online" moeten ook mogelijk zijn, of daar moeten we een andere oplossing voor bedenken.

### 1. Slechts een array met strings
Om strikt de usecase in enge zin mogelijk te maken zouden we kunnen volstaan met een Array of strings en duidelijke documentatie wat we hier verwachten.

### 2. Hergebruiken van addresses.
We definiëren voor gebouwen en organisaties op dit moment al adressen. `locations` zou een array met addresses kunnen zijn. Het "online" aspect ontbreekt dan.

### 3. Oplossing 2, maar met een keuze optie voor non-physical locations
`locations` als array zoals in oplossing 2, maar uitgebreid met de mogelijkheid om niet alleen adressen maar ook een ander "objecttype" op te nemen in de array. Dat andere objecttype zou een soort enumeratie of iets dergelijks kunnen zijn met non-physical locations, zoals `online`.

Niet direct relevant, maar wel interessant is de uitleg welke objecttypen het BAG register onderscheid:
https://imbag.github.io/praktijkhandleiding/objecttypen

### Requests and responses

Alle requests en responses waarin offerings voorkomen.

**Comment by jelmerderonde** [comment]
@hamrt ik heb dit issue toegevoegd n.a.v. het gesprek gisteren bij Project Studentmobiliteit, misschien kun jij er vast een blik op werpen?

**Comment by Marcel-Noordzij** [comment]
Onderstaande wil ik graag als overweging inbrengen voor het bepalen van de oplossing.

Ik weet niet of het voorstel om de locatie toe te voegen aan de offering werkt, of de functionele behoefte afdekt.

Als student wil ik bij EduExchange kunnen zien en filteren op vakken en/of minoren die op een voor mij gunstige locatie gegeven worden.
De offering wordt niet gebruikt in het zoekproces en komt pas later in beeld.

Los daarvan geldt dat niet elk SIS of elke instelling al offering (rooster) informatie beschikbaar heeft. Zeker als we naar de minoren kijken.
Inschrijven op de minor vindt eerder plaats dan aanmelden op de vakken die binnen de minor aangeboden worden.

Ook voor vakken die interessant zijn geldt dat de roosterinformatie bij het oriënteren (zeker als je als student naar het aanbod van het komend jaar gaat kijken) nog niet altijd bekend is. Zeker voor de vakken in de tweede helft van het jaar geldt dat het rooster in veel gevallen nog niet gemaakt is.
Ik denk dat het best lastig is om op een Offering object informatie vast te leggen en aan te bieden als dat object nog niet bestaat.

Verder zijn locaties niet alleen woonplaatsen, maar ook indicatoren als ‘in buurt van station’, ‘met OV bereikbaar’ en ‘online’ (zoals al opgemerkt).
Je zou kunnen stellen dat online een kenmerk van het vak (mode of delivery) die je al op een andere manier is opgelost.

Een array of strings zou kunnen werken voor de locatie, waarbij eduExchange dan dynamisch op de gevonden waarden in de array of strings een filter genereert. 
Nadeel hiervan is dat je verschillende schrijfwijzes kunt krijgen voor ‘bij het station’ en het filter niet meer eenduidig is.
Enumeratie zou voor deze meer locatie-informatie gerichte zaken wellicht handig zijn.

**Comment by jelmerderonde** [comment]
@Marcel-Noordzij je punt dat locatie wellicht niet thuishoort op Offering niveau snap ik. Ik denk dat we in v5 even goed moeten kijken hoe een locatie attribuut precies een plek kan krijgen bij bijv. Program, Course en Component. Vooral omdat er in RIO ook een relatie tussen een AangebodenOpleiding en OnderwijsLocatie tot stand gebracht moet kunnen worden.

**Comment by Marcel-Noordzij** [comment]
@jelmerderonde ik heb nog even wat zitten puzzelen en denken.
Het object dat we hiervoor zouden kunnen herbruiken is idd het address object (uit building).

Deze zou dan beschikbaar moeten komen als locations (array of addresses) op:
- programs
- courses

Bij de offerings van programs en courses is de informatie ook handig, alleen daar zie ik geen noodzaak om een array of addresses te maken. Een offering zal op 1 locatie worden gegeven is mijn verwachting, maar mogelijk dat het nuttig kan zijn om ook hier generiek te blijven en aan te geven dat een aangeboden opleiding of vak op meer locaties kan worden aangeboden.

Op components zit de ruimte, op basis waarvan je altijd kunt achterhalen waar deze zich bevind (room -> building -> address). Maar vanuit eenvoud kan ik me ook voorstellen dat daar ook het address gekoppeld wordt als optioneel object. 

Address bevat veel kenmerken, die niet persé nodig zijn, maar ze zijn allen optioneel, dus het is prettig om ze allemaal beschikbaar te hebben.

Het resultaat van bovenstaande zou dan zijn dat locations (array of addresses) moet worden toegevoegd aan:
- programs
- courses
- courses/offerings
- programs/offerings

Optioneel ook aan:
- components
- components/offering

Verder geldt dat ik me kan voorstellen dat de address/city als filter beschikbaar moet komen op programs en course.
Als ik kijk vanuit eduExchange, dan wil je daar ook evt. kunnen filteren op vakken / minoren die in bijvoorbeeld Rotterdam 
verzorgd worden. Maar dat zou je ook tot nader order 'client-side' kunnen oplossen en dan kan deze nu buiten beschouwing gelaten worden.

Tijdens de LDE sessies kwam de locatie ook naar voren als 'dicht bij station', 'makkelijk bereikbaar', 'parkeerplaatsen beschibkaar'. Ik denk dat we die beter buiten beschouwing kunnen laten en dat deze bij de description wordt opgenomen als informatie. Alternatief is om een uitbreiding te doen op het address object met een 'remark'. Daar zou je dan kenmerken van de locatie kunnen vastleggen.

Je opmerking over 'zonder fysieke locatie', bijvoorbeeld online, snap ik ook.
Ik weet alleen niet of dat een locatie is of een aanbodsvorm. Bij course heb je modeOfDelivery en die geeft al aan 'online', dus dan kun je address weglaten en snapt iedereen dat de cursus niet fysiek op een locatie wordt verzorgd.
Bij program en component is deze informatie over de aanbodsvorm niet beschikbaar. Je kunt bijvoorbeeld niet zeggen dat er sprake is van een toets of college dat online wordt afgenomen.

We zouden ook modeOfDelivery aan de verschillende objecten kunnen toevoegen, zodat ook daar kan worden aangegeven dat iets online wordt verzorgd.

**Comment by jelmerderonde** [comment]
@Marcel-Noordzij ik kan me zeker vinden in de oplossing die je schetst. De enige twijfel die ik nog heb is of we inderdaad de component `address` in volledigheid willen hergebruiken: een adres impliceert immers dat je tot op huisnummer-niveau weet waar iets is. Terwijl met name voor programs (en offerings), maar misschien ook wel voor courses (en offerings) dat detailniveau niet nodig is (misschien zelfs ongewenst).

Alternatief zou zijn dat we een nieuwe component toevoegen, misschien wel gewoon `location` en dat een vrij veld laten bijvoorbeeld.

Maar ik ben er nog niet over uit wat mijn eigen voorkeur heeft: jouw oplossing met address of het alternatief. Misschien dat @ruttromp ook even mee kan kijken?

**Comment by ruttromp** [comment]
Per optie mijn feedback:

1. toevoegen nieuw `location` attribuut aan Program en Course voor deze toepassing lijkt mij verwarrend. De inhoud hiervan kan overlappen met `address` wanneer het een fysieke locatie is en met `modeOfDelivery` wanneer het enkel online is af te nemen. Eigenlijk zou `address` dan omgevormd moeten worden naar de meer generieke `locations` oplossing.

1. het toevoegen van een verwijzing naar het bestaande `address` schema lijkt mij een betere keuze. Deze kan dan niet verplicht worden. Wanneer `modeOfDelivery` online is, kan `address` achterwege worden gelaten. Ook biedt `address` veel vrijheid om informatie wel/niet op te geven. Alleen `type` is hier verplicht.

Vragen aan @Marcel-Noordzij:
- volstaat het toevoegen van `address` aan Program, Course en Offering?
- betreft dit altijd 1 adres of kunnen dit er meerdere zijn (array)
- zal ik voor optie 2 een PR maken?

**Comment by Marcel-Noordzij** [comment]
Ja, als jij een PR kunt maken voor optie 2, dan graag.

Eén address is voldoende, ik zie geen behoefte om meerdere addressen op te geven.

**Comment by ruttromp** [comment]
Closed by #194
