### ISSUE TITLE
How to deal with future and historic changes (wrt RIO)

### ISSUE THREAD

**Issue by jelmerderonde** [open-education-api/specification#166]

**Comment by mpdejong** [comment]
1)	timelineOverride:
Een generieke manier om willekeurige attributen van een object een andere waarde te kunnen geven die voor een specifieke periode geldt, zowel in het verleden als in de toekomst.
Er zou een nieuw object `timelineOverride` moeten komen.
Met als attributen:
-	refId  (uuid)                                    uuid van het object waar deze timelineOverride bij hoort
-	startDatum (date)                           datum vanaf wanneer deze timelineOverride geldig is
-	eindDatum (date)                           datum tot (en met) wanneer deze timelineOverride geldig is
-	attributeName (string)                   naam van het attribuut
-	attibuteValue (string)                     aangepaste waarde van het attribuut

Ieder object binnen de OOAPI kan `timelineOverride `hebben.
Door in de query-parameter ‘expand’ `timelineOverride` mee te geven geef je aan alle timelineOverrides van het betreffende object in het result te willen krijgen. 

(Voorstel opgesteld door Arthur van Alten en Mark de Jong.)

**Comment by arthurvanalten** [comment]
Ik heb een voorbeelduitwerking van een timelineOverrides-attribuut op een program. 
Wat ik voorstel is dat een timelineOverride alleen op attributen van een object betrekking hebben.
Een timelineOverride heeft als attributen 
- startDate  (yyyy-MM-dd) 
- endDate   (yyyy-MM-dd) [optioneel]
- attributes  (array van name-value objecten)

Dit gaat goed samen met de eerder besproken mogelijkheid om extra attributen voor een specifieke afnemer te kunnen toevoegen aan de bestaande attributen door gebruik te maken van een zogenaamde prefix.
Voor RIO zouden dan bijvoorbeeld de volgend attributen aan een programma kunnen worden toegevoegd:
  "rio_deficientie": false,
  "rio_versneldTraject": false,
  "rio_propedeutischeFase": false,
  "rio_eisenWerkzaamheden": false,
  "rio_studiekeuzecheck": true,

Voorbeeld-JSON (Deze is gebaseerd op de JSON die op het MIRO-bord werd gebruikt voor de timelineOverrides-discussie.):
{
  "programId": "123e4567-e89b-12d3-a456-426614174000",
  "type": "program",
  "name": [
    {
      "language": "NL-nl",
      "value": "Biologie"
    },
    {
      "language": "EN-gb",
      "value": "Biology"
    }
  ],
  "abbreviation": "bio",
  "description": "Biology is the study of life",
  "ects": 180,
  "qualificationAwarded": "None",
  "lengthOfProgram": 36,
  "levelOfQualification": "6",
  "sector": "university education",
  "fieldsOfStudy": "0732",
  "crohoCreboCode": "59312",
  "learningOutcomes": [
    "string"
  ],
  "admissionRequirements": "Students need to be enrolled at qualifying institutions of higher education that participate in this alliance",
  "qualificationRequirements": "None",
  "link": "https://www.uu.nl/biologie",
  "ext": {},
  "rio_deficientie": false,
  "rio_versneldTraject": false,
  "rio_propedeutischeFase": false,
  "rio_eisenWerkzaamheden": false,
  "rio_studiekeuzecheck": true,
  "timelineOverrides": [
    {
      "startDate": "01-09-1990",
      "endDate": "31-08-2005",
      "attributes": [
        {
          "name": "eigenNaam",
          "value": "Biologie"
        },
        {
          "name": "link",
          "value": "https://biologie.uu.nl"
        },
        {
          "name": "rio_studiekeuzecheck",
          "value": false
        }
      ]
    },
    {
      "startDate": "01-09-2022",
      "attributes": [
        {
          "name": "name",
          "value": [
            {
              "language": "NL-nl",
              "value": "Biologie - levensstudies"
            },
            {
              "language": "EN-gb",
              "value": "Biology - studies of life"
            }
          ]
        },
        {
          "name": "rio_studiekeuzecheck",
          "value": false
        }
      ]
    }
  ]
}

**Comment by jelmerderonde** [comment]
Na discussie op 19 april met @arthurvanalten, @hamrt, @ruttromp en ikzelf hebben we besloten om:
- `timelineOverrides` toe te voegen, met:
- `startDate`, `endDate`, `object` (dat laatste is een herhaling van het hoofdobject, maar zonder `timelineOverrides`.
-

**Comment by jelmerderonde** [comment]
Closed by #197
