### ISSUE TITLE
[Change request]: update v5 with v4.1 changes that are not yet merged 

### ISSUE THREAD

**Issue by hermanvand** [open-education-api/specification#182]
### Organization

SURF

### Short description

v5 was duplicated from v4. some v4.1 changes did not make it to this v5. we need to fix this. See:
https://github.com/open-education-api/specification/compare/4.1

### Version

v5

**Comment by jelmerderonde** [comment]
@hermanvand goed punt. Het is misschien het makkelijkst om een nieuwe branch te maken vanaf de huidige 5.0 branch en de wijzigingen handmatig opnieuw toe te passen. De markdown changes en de changelog zijn al toegepast op 5.0. Dus het gaat alleen om de typo en het ext object bij collection responses.

**Comment by hermanvand** [comment]
ext objects are added . The typo was already fixed :-)

**Comment by jelmerderonde** [comment]
Fixed by #191
