### ISSUE TITLE
Overview of all attributes

### ISSUE THREAD

**Issue by jelmerderonde** [open-education-api/specification#183]
Ter voorbereiding op de verdere uitwerking van OOAPI v5 heb ik alle attributen van OOAPI v4, eduAPI en RIO naast elkaar gelegd.

Per attribuut doe ik een aanbeveling wat er mee zou moeten gebeuren.

Dit issue is gerelateerd aan:

- #164, analoog aan eduAPI heb ik een locations attribuut toegevoegd aan Program, Course en Component
- #162, ik heb het mainLanguage attribuut toegevoegd aan Program, Course en Component. Het vervalt bij alle offerings.
- #156, ik heb profileOfProgram verwijderd
- #155, analoog aan eduAPI heb ik een locations attribuut toegevoegd aan Program, Course en Component
- #154, ik heb alle timevelden ook gelijk opgenomen in dit overzicht
- #111, ik heb length/duration aan Course en Component toegevoegd
- #106, in de sheet is ook opgenomen welke attributen nodig zijn voor welk RIO object

Indien akkoord dan zou deze sheet, zodra we een beslissing hebben genomen over het wel/niet toevoegen van een extra object aan OOAPI, uitgwerkt kunnen worden in de specificatie.

[All attributes.xlsx](https://github.com/open-education-api/specification/files/8454036/All.attributes.xlsx)

**Comment by jelmerderonde** [comment]
@hermanvand, @hamrt en @ruttromp kunnen jullie de sheet bekijken die ik toegevoegd heb aan dit issue?

**Comment by hermanvand** [comment]
Ja, ik heb er naar gekeken vanuit het oogpunt van studentmobiliteit & gebruik van minoren/programs. Het lijkt er op dat we in ieder geval hiermee, net als intekenen op courses, intekenen op minoren mogelijk kunnen maken Door de extra velden die aan een program zijn teogevoegd. top!

Verder zit ik nog een beetje met het vrije veld 'theme'. Ik zie naast het gecontrolleerde isced veld 'fieldsOfStudy' ook wel bestaanrecht voor een vrijer veld 'theme'. Op zich zou dat best passen in de algemene spec. Anders nemen we in het kader van studentmobiliteit deze alsnog op in ext{}

Daarnaast gaat er iets mis met het attribuut course:reference. Die staat er 2x in, op regel 41 en 45. En volgen mij is er geen referentie voor programOffering en componentOffering.

Over het attribuut primaryCode heb ik een vraag. Want binnen studentmobiliteit gaan we er vanuit dat 'abbreviation' de courseCode bevat. Wordt dat dan de primaryCode? Zo ja, je zou dat ook expliciet kunnen maken, net als types. Dus niet overal primaryCode, maar programCode, courseCode, componentCode. Dat is dan wel duidelijk.

Als laatste zie ik targetGroup niet terugkomen, maar dat wordt ook besproken in issue #160 Al zou ik dat dan ook wel in dit overzicht verwachten.

**Comment by jelmerderonde** [comment]
Dank voor de feedback @hermanvand. Ik heb een nieuwe versie gemaakt en toegevoegd aan het issue:

> Verder zit ik nog een beetje met het vrije veld 'theme'. Ik zie naast het gecontrolleerde isced veld 'fieldsOfStudy' ook wel bestaanrecht voor een vrijer veld 'theme'. Op zich zou dat best passen in de algemene spec. Anders nemen we in het kader van studentmobiliteit deze alsnog op in ext{}

Ik ben hier op zich niet op tegen, maar weet je zeker dat je er een vrij veld van wil maken? Een extensible enumeration zou ook kunnen misschien.

> Daarnaast gaat er iets mis met het attribuut course:reference. Die staat er 2x in, op regel 41 en 45.

Gefixt.

>  En volgen mij is er geen referentie voor programOffering en componentOffering.

Die voor `programOffering` is er wel, zie regel 41 in het nieuwe bestand. Voor componentOfferings is die er niet, maar dat klopt. Deze file geeft een overzicht van alle attributen. Voor de volledigheid heb ik ook de attributen opgenomen die verwijzen naar andere (bovenliggende) objecten, als references. Maar er is geen één object dat met een attribuut verwijst naar `componentOfferings`. Offerings van een Component vragen we op via een pad `/component/{componentId}/offerings`. Of misschien via een expand.

> Over het attribuut primaryCode heb ik een vraag. Want binnen studentmobiliteit gaan we er vanuit dat 'abbreviation' de courseCode bevat. Wordt dat dan de primaryCode? Zo ja, je zou dat ook expliciet kunnen maken, net als types. Dus niet overal primaryCode, maar programCode, courseCode, componentCode. Dat is dan wel duidelijk.

Over `primaryCode`: ik heb die voor de volledigheid gekopieerd vanuit eduAPI, ik vond het wel een aardig mechanisme. Maar ik weet dat @ruttromp nog op zijn lijstje heeft staan om even goed te kijken naar deze en ook `otherCodes` vanuit eduAPI. Dus ik laat die keuze even aan hem

> Als laatste zie ik targetGroup niet terugkomen, maar dat wordt ook besproken in issue https://github.com/open-education-api/specification/issues/160 Al zou ik dat dan ook wel in dit overzicht verwachten.

Die moet er inderdaad nog bij, al weten we nog niet hoe het preices gaat heten en werken.

**Comment by hermanvand** [comment]
Top. Nog even een aanvulling.

> > Verder zit ik nog een beetje met het vrije veld 'theme'. Ik zie naast het gecontrolleerde isced veld 'fieldsOfStudy' ook wel bestaanrecht voor een vrijer veld 'theme'. Op zich zou dat best passen in de algemene spec. Anders nemen we in het kader van studentmobiliteit deze alsnog op in ext{}
> 
> Ik ben hier op zich niet op tegen, maar weet je zeker dat je er een vrij veld van wil maken? Een extensible enumeration zou ook kunnen misschien.
> 

De praktijk wijst uit dat het veel moeite kost om afspraken te maken over een set thema's. Daarom worden croho en isced in de praktijk ook niet veel gebruikt. (groepen van) Instellingen hanteren net andere benamingen. Vandaar dat ik dacht aan een vrij veld en niet aan een enumeration. Maar als een extensible enumeration betekend dat instellingen daar zelf waarden aan toe kunnen voegen, dan zou dat ook kunnen. 

> > Daarnaast gaat er iets mis met het attribuut course:reference. Die staat er 2x in, op regel 41 en 45.
> 
> Gefixt.
> 
> > En volgen mij is er geen referentie voor programOffering en componentOffering.
> 
> Die voor `programOffering` is er wel, zie regel 41 in het nieuwe bestand. Voor componentOfferings is die er niet, maar dat klopt. Deze file geeft een overzicht van alle attributen. Voor de volledigheid heb ik ook de attributen opgenomen die verwijzen naar andere (bovenliggende) objecten, als references. Maar er is geen één object dat met een attribuut verwijst naar `componentOfferings`. Offerings van een Component vragen we op via een pad `/component/{componentId}/offerings`. Of misschien via een expand.

Dit is een misverstand denk ik. Ik bedoel het andersom. Wat ik bedoel te zeggen is dat programOffering en componentOffering geen reference naar een course hebben. De kruisjes in de velden 45i en 45k bestaan volgens mij niet.
