### ISSUE TITLE
[Change request]: add consumer element for specific consumer extensions

### ISSUE THREAD

**Issue by hamrt** [open-education-api/specification#195]
### Organization

SURF

### Project

v5

### Contact Details

ronald.ham@surf.nl

### Short description

consumer attribute array should be implemented to suit different use cases in this case RIO will be the first

### Version

v5

### Usecase

RIO communication with attributes that are specific t this usecase and no other

### Proposed solution

create a file structure that allows for these extra arrays
a separate directory for consumer attributes that can than be added on the fly

**Comment by jelmerderonde** [comment]
Closed by #197
