### ISSUE TITLE
Bring back certain removed POSTS

### ISSUE THREAD

**Issue by hamrt** [open-education-api/specification#26]
Currently all post actions have been removed. I would like to propose POST options that facilitate the following use cases:

- The ability for students to enroll in a course 
- The ability for students to add a photograph of themselves
- The ability for students to use the schedules to add their own data or at least combine the schedule data generated by the OO-API with their own calendars.

**Comment by joostfarla** [comment]
OK, lets discuss this in the next meetup!

**Comment by usapieter** [comment]
Is part of the 'notifications' architecture -> there is a proposal in there how a post and how a delete should work.

**Comment by fransward** [comment]
Need additional use cases

**Comment by hamrt** [comment]
Close for now wait until the questions for POST requests are more specific
