### ISSUE TITLE
Add identifiers for levels & room types

### ISSUE THREAD

**Issue by usapieter** [open-education-api/specification#28]
For Universiteit Leiden we are looking to provide a list of all levels (bachelor, master, associate etc) of courses. 'Levels' are defined as response in some items of the OOApi (for example 'courses'). 

This list of levels is used to set up a UI in a mobile app to let users first select a level, than a educational department, and then add courses of that department to their schedule. 

Now, I'm wondering - if we were to provide a list of all available levels - would that be considered part of 'courses' - ie GET /courses/levels

or levels a general item - and would these be separate of courses? - ie GET /levels/

Or, are levels part of an educational plan (at this moment, they are not part of the educational plan response data) - ie get /educational-plans/levels?

In our view, levels are a general item - and not directly part of courses nor educational plans - so our initial plan would be to go ahead with a GET /levels.

As this is not part of the OOApi yet, I'm not proposing to add this for 2.0 - just want to know your general thoughts, and if you'd support at a later moment in time to add a /levels.

**Comment by joostfarla** [comment]
If we use the same enumerable property for different endpoints, we might be able to use the root/meta endpoint (as discussed in https://github.com/open-education-api/specification/issues/37) as a place to publish the possible values for the specific implementation. This might be interesting for other enumerables also, without the need to create extra endpoints for simple value sets (which will probably never change)?

**Comment by fransward** [comment]
Needs more discussion. get /educational-plans/levels seems to have the most support for now.
with added filtering option.
Can we discuss this here ?

**Comment by fransward** [comment]
Add an ID in the metadata endpoint for OOAPI 3.0

**Comment by fransward** [comment]
Done
