### ISSUE TITLE
[Change request]: Force organizations name to always be a list

### ISSUE THREAD

**Issue by Tomeriko96** [open-education-api/specification#289]
### Organization

Vrije Universiteit Amsterdam

### Short description

The names field in organizations was found to be either a string or a list. 

### Version

v5

### Proposed solution

Consider having a list be the default format of this field, even for a single entry.

**Comment by jelmerderonde** [comment]
@Tomeriko96, sorry we are just getting up to speed again handling open issues, so we are a quite late with asking these questions. Nevertheless, could you explain a bit more what you mean with this issue? The current Organization `name` field is an array of LanguageTypedStrings. So it is already defined as a list in version 5 of the specification.

**Comment by Tomeriko96** [comment]
Hi @jelmerderonde 

I cannot recreate the issue, with the code I used almost a year ago. Therefore I believe we can close this issue.
