### ISSUE TITLE
[Change request]: RIO opleidingsvorm > OOAPI mapping

### ISSUE THREAD

**Issue by remco-jak** [open-education-api/specification#295]
### Organization

SURF / Fontys

### Project

RIO mapper

### Contact Details

remco.jak@surf.nl

### Short description

RIO opleidingsvorm values `COACHING` , `ZELFSTUDIE` and `LEZING` do not map to OOAPI modeOfDelivery values. ( [OOAPI > RIO mapping](https://openonderwijsapi.nl/#/technical/consumers-and-profiles/rio?id=modeofdelivery-opleidingsvorm) )

Updating existing entities in RIO could result in unintended modifications of it's opleidingsvorm value if current OOAPI specification is used.

At this moment the issue for Fontys is limited to `COACHING`, but `ZELFSTUDIE` and `LEZING` are valid values in their systems as well.

### Version

v5

### Usecase

Updating / adding RIO entities with all opleidingsvorm options available in RIO.

### Which institutions support this change?

Fontys Hogescholen

### Proposed solution

Extend OOAPI modeOfDelivery with RIO opleidingvorm values, possibly through the use of consumer RIO.

### Requests and responses

modeOfDelivery exists in objects
programs
courses
components
offerings

For RIO only programOfferings and courseOfferings are used to map modeOfDelivery:

/offerings

### What is your question for the OOAPI work group?
Fontys is one of the first institutes participating in the OOAPI-RIO project to actively update the RIO register with their education data in OOAPI format. Could the OOAPI workgroup provide insight in the timeline to be expected for this issue?

**Comment by remco-jak** [comment]
A discussion with @jelmerderonde @hamrt @hermanvand en @remco-jak on May 16 2023 resulted in a solution proposal:

An optional `modeOfDelivery` attribute is added to the the RIO consumer.

Only when present, the value of this optional `modeOfDelivery` attribute will override the objects `modeOfDelivery` value. This value will be mapped one-on-one  to `opleidingsvorm` in RIO


| modeOfDelivery RIO consumer | opleidingsvorm RIO   | description          |
| -------------------- | ------------- | -------------------- |
| online               | ONLINE               | Online               |
| hybrid               | KLASSIKAAL_EN_ONLINE | Klassikaal en online |
| situated             | KLASSIKAAL           | Klassikaal           |
| lecture              | LEZING               | Lezing               |
| self-study           | ZELFSTUDIE           | Zelfstudie           |
| coaching            | COACHING             | Coaching             |


If the RIO consumer does NOT contain a `modeOfDelivery` attribute, the value of the object's `modeOfDelivery` is mapped as currently described here [OOAPI > RIO mapping](https://openonderwijsapi.nl/#/technical/consumers-and-profiles/rio?id=modeofdelivery-opleidingsvorm):

| modeOfDelivery OOAPI   | opleidingsvorm RIO   | description          |
| -------------------- | ------------- | -------------------- | 
| distance-learning     | ONLINE               | Online               |
| on campus           | KLASSIKAAL           | Klassikaal           |
| online                    | ONLINE               | Online               |
| hybrid                   | KLASSIKAAL_EN_ONLINE | Klassikaal en online |
| situated              | KLASSIKAAL           | Klassikaal           |

(no mapping to  `LEZING`, `ZELFSTUDIE` and  `COACHING`)

**Comment by mdemare** [comment]
This will work for the eduhub-mapper.

**Comment by mdemare** [comment]
@remco-jak Which object will contain the consumer with the modeOfDelivery, the program, or the offering?

**Comment by remco-jak** [comment]
@mdemare programOfferings and courseofferings both contain the consumer with the optional modeOfDelivery. So, only offerings contain this RIO consumer.

**Comment by remco-jak** [comment]
closed by #297
