### ISSUE TITLE
Fix naming and formatting inconsistencies

### ISSUE THREAD

**Issue by joostfarla** [open-education-api/specification#3]
A lot of naming and formatting inconsistencies can be found in the spec. 

Naming examples:
* Singlar vs plural nouns, e.g. `course` vs `courseId` vs `courses` for multi-value fields
* Semantic differences, e.g. `person` vs `user` vs `teacher`
* Casing inconsistencies, e.g. `userid` vs `userId`
* URI vs ID, e.g. `student` in `GET /courseresults/{userId}` is a URI, not an ID

Formatting examples:
* Order/presence of fields, e.g. primary key first, `lastModified` last. `GET /newsitems` doesn't even return a`lastModified` field
* Not all endpoints provide primary keys, e.g. `courseresults`
* Nesting (some endpoints like `course.lastModified` in `GET /courseresults/{userId}` nest other resources, others do not). The way of nesting is not very common.

What should be done here:

* Discuss and define naming and formatting conventions in the [contributions](https://github.com/open-education-api/specification/blob/v1/CONTRIBUTING.md) document
* Fix inconsistencies in the spec
* Discuss whether we are going to fix this in v1 or v2 (which will cause some backwards-compatibility breaks)

**Comment by usapieter** [comment]
i would encourage this discussion!

Maybe this could better be done in a face-to-face workgroup setting, than trying to get all inconsistenties out in separate github postings?

**Comment by joostfarla** [comment]
Sounds good to me (with a smaller setting probably). What do you think, @fransward ?

**Comment by fransward** [comment]
Joost will do a final check

**Comment by joostfarla** [comment]
Fixed
