### ISSUE TITLE
[Change request]:  specification

### ISSUE THREAD

**Issue by arthurvanalten** [open-education-api/specification#309]
### Organization

Inholland

### Contact Details

arthur.vanalten@inholland.nl

### Short description

BUG:

return-items for GET /education-specifications/{educationSpecificationId}/education-specifications are wrong.
it says that the items are of type: 'Array of objects (Course)'
That should be of type: 'Array of objects (EducationSpecification)'

### Version

v5

### Proposed solution

This is a bug. so this have to be changed in de specification

### Requests and responses

GET /education-specifications/{educationSpecificationId}/education-specifications

**Comment by hamrt** [comment]
part of pr #310

**Comment by hamrt** [comment]
fixed in pr #311
