### ISSUE TITLE
date of birth missing from 'persons' output

### ISSUE THREAD

**Issue by usapieter** [open-education-api/specification#33]
could we add it (as optional) field to the output of persons?

Question: what DATE format is to be used in the OOApi anyway?

DD-MM-YYYY?

**Comment by fransward** [comment]
Will add in the JSON output as optional field: dateOfBirth, type date ISO 8601

**Comment by joostfarla** [comment]
Will be fixed in https://github.com/open-education-api/specification/pull/49.

**Comment by joostfarla** [comment]
Merged.
