### ISSUE TITLE
Should courseResult (output testResults) be under links?

### ISSUE THREAD

**Issue by usapieter** [open-education-api/specification#34]
![schermafdruk 2017-05-11 13 06 39](https://cloud.githubusercontent.com/assets/7964634/25946287/b7a18f3a-364a-11e7-8af3-2688165381d3.png)
As it's a link to the courseresult where the testresult is part of, shouldn't it be under the link section of the output?

**Comment by joostfarla** [comment]
Correct, we have only implemented the basic structure for now. Existing links have still to be converted to hypermedia controls. Will be continued in https://github.com/open-education-api/specification/issues/36.
