### ISSUE TITLE
Convert existing relations to hypermedia controls

### ISSUE THREAD

**Issue by joostfarla** [open-education-api/specification#36]
This issue describes the remaining work for implementing the HAL mediatype. We have yet implemented the HAL format, including links for pagination and self-links. The work that still has to be done is converting existing links to hypermedia controls.

**Comment by joostfarla** [comment]
Created a PR for the link conversion. Todo:
* Create links for educational department additions
* Check all link names
* Check all link cardinalities
* Check all links: required vs optional links
* Check all links: link collection vs single link to filtered collection
I need someone with domain knowledge to help me out with these final steps.

**Comment by fransward** [comment]
Joost, Tom and Pieter will look into this
