### ISSUE TITLE
Add root endpoint for exposing the service metadata

### ISSUE THREAD

**Issue by joostfarla** [open-education-api/specification#37]
Create a root endpoint, which returns metadata about the service. For example:

* Which modules/endpoints are offered?
* Supported languages
* Link to the OAS/Swagger spec
* Contact information
* ...

**Comment by fransward** [comment]
- Name of institution
- link to documentation:
   - YAML/JSON reference
  -  link to the HTML user documentation
- Logo (pref SVG, png, jpg) - small, medium, large - dimensions
- OOAPI API Contact info (email) -> COULD BE IN THE DOCUMENTATION
- Terms: privacy statement and general terms
- Supported languages (for V3)
- Supported levels

**Comment by joostfarla** [comment]
Added in v2.1 branch: https://rawgit.com/open-education-api/specification/v2.1/docs.html

**Comment by fransward** [comment]
Fixed in 2.1
