### ISSUE TITLE
Remove geo- and full-text support 

### ISSUE THREAD

**Issue by joostfarla** [open-education-api/specification#38]
It seems spatial proximity and full-text searching is too complex for most backend systems. Therefore, we agreed to remove them from the spec.

**Comment by joostfarla** [comment]
Furthermore, we decided to remove `lat`/`lon` from the person resource, but keep them for buildings. Two questions left:
* Do we want to keep the `lat`/`lon` parameters for `Room`, or is `Building` enough?
* Do we need to keep the `altitude` parameter (for `Room` and `Building`)?

**Comment by fransward** [comment]
lat/lon only for Building is enough
altitude can disappear
