### ISSUE TITLE
Are there reasons why the spec should NOT be read-only?

### ISSUE THREAD

**Issue by joostfarla** [open-education-api/specification#4]
The Open API spec is intended to create a uniform interface and increase interoperability between systems. I was wondering if we really need to support write operations, since this will mostly be handled by external systems. How realistic is it that a person/student/teacher would be "created" through the API? This sounds to me like a process which is too complex to be handled by the Open Education API. What are the use cases where we would need a writeable interface?

**Comment by joostfarla** [comment]
As discussed in today's meeting, we proposed to make v2 read-only. One should be allowed to implement write operations, but it's not part of this specification. In the future, we might add write operations for specific use cases.

**Comment by usapieter** [comment]
👍

**Comment by joostfarla** [comment]
Thanks @pgh70 👍
