### ISSUE TITLE
Rooms - "Type" attribute

### ISSUE THREAD

**Issue by usapieter** [open-education-api/specification#48]
I think adding a 'type' attribute to the "rooms" resource would be wise: a room within a building has purpose, and in a typical usecase a user is not looking for any room, but a room for a purpose to do/accomplish something: to study alone (quiet), to discuss with teammembers about an assignment), to use the PC facilities, attend a class, etc. 

Two questions:

1) is adding a type attribute for rooms (and querystring to sort on type) a wise idea? 

2) what general types would then be useful to describe the purpose of a 'room'?

My idea's (for now:)

- lecture hall (collegezaal)
- PC lab (with "workspaces")
- general purpose (gang, hal, entree, restaurant etc)
- project room (werkgroep ruimte)
- study / quiet room (studieplek)

**Comment by fransward** [comment]
Default list of attributes per institution could be part of the /root endpoint.
List and filter option.

**Comment by joostfarla** [comment]
Added in v2.1 branch: https://rawgit.com/open-education-api/specification/v2.1/docs.html

**Comment by fransward** [comment]
Fixed in 2.1
