### ISSUE TITLE
Define error response format

### ISSUE THREAD

**Issue by joostfarla** [open-education-api/specification#5]
The v1.0 PDF document describes the HTTP status codes that an error response can have. However, it would be good to describe how the error response body is formatted to be able to provide more specific information about the error.

There are existing media types available for this, for example [problem+json](https://tools.ietf.org/html/rfc7807). A simple error response could look like this:

```json
{
  "status": 400,
  "title": "VALIDATION_ERROR",
  "detail": "Some request parameters are invalid.",
  "params": {
    "name": "The field 'name' can not be longer than 100 characters."
  }
}
```

In addition (maybe v2?), we could define standard [error types and instance URLs](https://tools.ietf.org/html/rfc7807#section-3.1) to link to HTML pages describing the problem.

**Comment by usapieter** [comment]
we have been adding response errors and description already - and would support the standard to describe how error response body is formatted.

{
"id": "200",
"status": "200",
"message": "OK",
"moreInfo": "Successfull",
"language": "en"
}

Please bear in mind that the actual reason as listed in the 'name' is not always clear. What needs to be done in that case? No name to be supplied? Or copy the info from 'detail'?

**Comment by joostfarla** [comment]
The `name` argument is just an example of specific messages of request bodies (for write operations) with an attribute called `name`. In most (read-only) cases, the `params` object will not exist.

**Comment by fransward** [comment]
Conform RFC7807
