### ISSUE TITLE
Is partial updating of a resource supported?

### ISSUE THREAD

**Issue by joostfarla** [open-education-api/specification#6]
The current spec supports `POST` calls on collection resources (e.g. `/persons`) and `PUT` calls on instance resources (e.g. `/persons/john`). According to the HTTP spec, [`PUT`](https://tools.ietf.org/html/rfc2616#section-9.6) calls are meant to store the request payload as a modified version of the resource identified by the URI. In short, this means that the resource is **replaced** by the resource representation sent in the payload (body).

The current HTTP spec does not support partial updating of a resource, however there are workaround to do this:
* Provide [`PATCH`](https://tools.ietf.org/html/rfc5789) method. This spec is still in draft state and forces the sender to create [JSON-PATCH documents](https://tools.ietf.org/html/rfc6902)
* Overload [`POST`](https://tools.ietf.org/html/rfc2616#section-9.5) method on instance resource URIs to support partial updates. Only the fields sent in the request will be updated on the resource.

I would vote for the second option and drop `PUT` support to keep things simple.

**Comment by usapieter** [comment]
We have not seen this use-case before - but if we would have to choose, we would vote for option 2 as well.

**Comment by joostfarla** [comment]
This issue is obsolete for now, since we're dropping all writeable operations.
