### ISSUE TITLE
Testing the OpenEducationAPI

### ISSUE THREAD

**Issue by SwPractitioner** [open-education-api/specification#60]
Hi!
@joostfarla 

If i have to test this api then is there any URL for this api to which i can send http requests and check their output?
OR
i have to download this project on my pc and run the api from there?

**Comment by joostfarla** [comment]
Hi @SwPractitioner! This project is only the specification, so there is no working endpoint. Multiple organizations will build their own implementations of this spec. To see how the responses look like, you can find examples in the sidebar of the documentation page: https://rawgit.com/open-education-api/specification/v2/docs.html

**Comment by SwPractitioner** [comment]
Thanks @joostfarla for reply.
