### ISSUE TITLE
Link to image URL (newsfeed items) should be specified as "string <uri>"

### ISSUE THREAD

**Issue by usapieter** [open-education-api/specification#62]
https://www.dropbox.com/s/hx8iz89ghqk0c90/Schermafdruk%202017-07-17%2020.05.28.png?dl=0

For consistenty purposes, should be specified as a "string <uri>" - as all other links are specified like that as well

**Comment by joostfarla** [comment]
Fixed in https://github.com/open-education-api/specification/pull/63.
