### ISSUE TITLE
filters but no values for courses

### ISSUE THREAD

**Issue by hamrt** [open-education-api/specification#65]
The course endpoint allows for filters on:
 faculty
 educationalDepartment
 educationalPlan
 courseGroup
Howevere, there aren't any attributes with these names in the endpoint. Shouldn't the be atleast optionally there?

**Comment by joostfarla** [comment]
Sounds logical. We could add them as (optional) links, in the same way we have links to other resource types.

**Comment by joostfarla** [comment]
We first need to discuss the cardinality of these relations. Are they one-to-one or one-to-many? Is it possible for a course to be part of multiple educational plans/departments? And what about faculty and course group?

**Comment by joostfarla** [comment]
For now, I've added them as one-to-many relations, see proposal here:
https://rawgit.com/open-education-api/specification/v2.1/docs.html

**Comment by fransward** [comment]
Fixed in 2.1
