### ISSUE TITLE
Logo of institution as an endpoint

### ISSUE THREAD

**Issue by hamrt** [open-education-api/specification#69]
By adding a logo as endpoint for an institution the default logo can be added to the information that is provided. This allows for services to visually present ownership of information or provide a default logo for an institution.

**Comment by joostfarla** [comment]
Can we add this as a new property on the "Faculties" endpoint (since a faculty can be of type institute, faculty, domain, etc)? Or are you proposing a "global" logo for each API implementation?

**Comment by joostfarla** [comment]
Same question goes for https://github.com/open-education-api/specification/issues/68.

**Comment by hamrt** [comment]
I’d like to propose a whole new endpoint for this as the image is not for a faculty as such but for a whole institution/organisation

In the current model we did not include the institution/organisation as such since we infer the institution form the base url of an instance. 

 

 

Van: Joost Farla [mailto:notifications@github.com] 
Verzonden: maandag 19 maart 2018 17:53
Aan: open-education-api/specification <specification@noreply.github.com>
CC: Ronald <ronald.ham@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [open-education-api/specification] Logo of institution as an endpoint (#69)

 

Can we add this as a new property on the "Faculties" endpoint (since a faculty can be of type institute, faculty, domain, etc)? Or are you proposing a "global" logo for each API implementation?

**Comment by joostfarla** [comment]
OK clear! It might be an interesting option to bundle this issue together with https://github.com/open-education-api/specification/issues/37 (root endpoint). We could provide a single endpoint for all metadata, like:
- Institution name, logo, etc
- Contact information
- URL to the docs
- URL to the terms / privacy statement (see also: https://github.com/open-education-api/specification/issues/68)

**Comment by fransward** [comment]
Closed in favour of issue #37
