### ISSUE TITLE
Define constraints for parameters

### ISSUE THREAD

**Issue by joostfarla** [open-education-api/specification#7]
Currently, only the data type of (query/body) parameters are defined. However, it lacks the constraints of these parameters. Examples are:

* Min/max lengths of string values
* Future vs historical date times
* Number constraints (decimals, positive, range etc)
* Min/max number of items in arrays/collections

These should be defined in the spec using JSON Schema.

**Comment by usapieter** [comment]
I'm not sure this is needed in a standard? 

Although I like to be as accurate  as possible in a standard - i feel this is maybe making the standard too strict.

If we won't adopt these limits, what would possibly go wrong?

**Comment by joostfarla** [comment]
Since we decided to remove all writeable operations, this is of less importance.

**Comment by usapieter** [comment]
Should this still be included in the V2 specs?

**Comment by joostfarla** [comment]
We discussed to do this on a very minimum level. I've just added a commit for this:
https://github.com/open-education-api/specification/commit/b8bcfa2336a6b15cdb2cc01ea8349ea729fd0ae0
