### ISSUE TITLE
Add layering in courses to allow for scheduling of learningActivities

### ISSUE THREAD

**Issue by hamrt** [open-education-api/specification#74]
Currently there is only a course provided within the specification this proves to be a good fit for study guides, but perhaps less for enrolling into a course (which usually is based on a specific course at a specific allocaed time slot taught by a specific set of teachers) or getting information on the types of activities that take place within the course which provides details on the format of the specific activity (HC/WC/P). /etc.

**Comment by fransward** [comment]
Implemented in OOAPI 3.0
