### ISSUE TITLE
Collection vs instance representations for course- and test results inconsistent

### ISSUE THREAD

**Issue by joostfarla** [open-education-api/specification#8]
For all endpoints, except course- and test results, there are 2 types of resources:
- collection endpoint (e.g. receive a list of all buildings)
- instance endpoint (e.g. receive details for one specific building)

The course- and test results are different. The collection URIs seem to serve some kind of aggregation instead of a list.

Simplified version of [`GET /courseresults/{userId}`](https://rawgit.com/open-education-api/specification/v1/docs.html#tag/course-results%2Fpaths%2F~1courseresults~1%7BuserId%7D%2Fget):

```json
[
  {
    "student": "john",
    "course": [
      "science"
    ],
    "course.lastModified": "2016-11-25T16:14:25Z"
  }
]
```

Simplified version of [`GET /courseresults/{userId}/{courseId}`](https://rawgit.com/open-education-api/specification/v1/docs.html#tag/course-results%2Fpaths%2F~1courseresults~1%7BuserId%7D~1%7BcourseId%7D%2Fget):

```json
{
  "course": "science",
  "testResults": [
    "test-result-1",
    "test-result-2"
  ],
  "lastModified": "2016-11-25T16:14:25Z",
  "grade": "8.5",
  "comment": "Some feedback",
  "passed": true
}
```

I would expect the collection resource to serve a list of all course results for the given user.

```json
[
  {
    "course": "science",
    "testResults": [
      "test-result-1",
      "test-result-2"
    ],
    "lastModified": "2016-11-25T16:14:25Z",
    "grade": "8.5",
    "comment": "Some feedback",
    "passed": true
  },
  {
    "course": "math",
    "testResults": [
      "test-result-3"
    ],
    "lastModified": "2016-11-25T16:14:25Z",
    "grade": "7.1",
    "comment": "Some feedback",
    "passed": false
  }
]
```

Can we reconsider this approach and make it consistent across all endpoints?

**Comment by usapieter** [comment]
I like consistency, so: yes 👍

**Comment by joostveerman** [comment]
The HU like this too!!

**Comment by fransward** [comment]
Joost will have a second look
