### ISSUE TITLE
Embed essential properties of related resources

### ISSUE THREAD

**Issue by joostfarla** [open-education-api/specification#9]
Multiple resource types are linked together by *foreign keys*, in a similar way how this is handled in relational databases. A resource contains references to other resources by returning the unique identifier of the related resource (e.g. a person resource contains IDs of the groups the person is member of). Example:

```json
{
  "userId": "123",
  "givenname": "Joost",
  "groups": ["1", "3", "5"]
}
```

From the perspective of a user interface (e.g. a persons profile page), you would probably want to show the group's human-readable names instead of the (technical) identifiers. To achieve this, a client application now has to do 3 extra requests (so 4 in total) to the *groups* endpoint to get the related group names. Therefore, it would make more sense to embed/include the most essential properties of related resources. Example:

```json
{
  "userId": "123",
  "givenname": "Joost",
  "groups": [
    {
      "groupId": "1",
      "name": "Group 1"
    },
    {
      "groupId": "3",
      "name": "Group 3"
    },
    {
      "groupId": "5",
      "name": "Group 5"
    }
  ]
}
```

What the essential fields are can differ per resource type and has to be determined based on domain-specific knowledge.

**Comment by usapieter** [comment]
I completely agree with the point Joost is making: by providing it this way, the number of API calls can be reduced - and if the group ID is available, usually the group name is available as well.

**Comment by joostveerman** [comment]
The HU has implemented this already by using custom fields. Changing this into the standard has our commitment.

**Comment by joostfarla** [comment]
Feature is implemented and the remaining work will be continued in https://github.com/open-education-api/specification/issues/36.
