### ISSUE TITLE
Discuss enumerations for v4

### ISSUE THREAD

**Issue by jelmerderonde** [open-education-api/specification#90]
The [draft v4 specification](https://open-education-api.github.io/specification/v4/docs.html) contains more enumerations than previous versions. The reasoning behind this choice is that this will make it easier to create applications that operate across more than one institution. Ideally the enumerations have options that correctly describe all the data we want to with the OOAPI. Below you can find the enumerations and all the options currently proposed in v4. Any feedback or discussion concerning these enumerations is very welcome!

# organization
## type
- root
- institution
- department
- faculty

# person
## affiliation
- student
- employee
- guest
## gender
- m
- f
- u
- x
## ICERelation
- partner
- parent
- other

# program
## type
- program
- minor
- honours
- specialization
- electives
- module
- track
- joint-degree
## qualificationAwarded
- AD
- BA
- BSc
- LLB
- MA
- MSc
- LLM
- PhD
## levelOfQualification
- 1
- 2
- 3
- 4
- 4+
- 5
- 6
- 7
- 8
## sector
- mbo
- hbo
- wo
## fieldsOfStudy
- ISCED-F codes

# courses
## level
- mbo 3
- mbo 4
- associate degree
- bachelor
- master
- doctoral
## modeOfDelivery
- distance-learning
- face-to-face
- hybrid

# components
## type
- test
- lecture
- practica
- werkcollege
- seminar

# offering
## type
- program
- course
- component
## resultValueType
- PF
- USletter
- UKletter
- 100
- 10
## modeOfStudy
- full-time
- part-time
- dual
- self-paced

# association
## type
- programOffering
- courseOffering
- componentOffering
## role
- student
- lecturer
- student assistent
- coordinator
- guest
## state
- pending
- canceled
- denied
- associated

# room
## type
- general purpose
- lecture hall
- pc lab
- office
- workspace

# other
### type
- postal
- visit
- deliveries

**Comment by hamrt** [comment]
The component types are currently in dutch as well as english. Perhaps we should choose:

- test
- lecture
- labratory session
- pracitcal class
- workshop
- seminar

**Comment by JanHendrikvanSchaik** [comment]
Components types van Saxion zijn:
CN          Consultatie
HC          Hoorcollege
PJ           Project
PR          Practicum
VL          Vaardigheidsles
WC         Werkcollege
WS         Workshop
XC          Excursie
XT           Extern
ZS           Zelfstudie

**Comment by jelmerderonde** [comment]
Bij Rooms ook tentamenlocaties toevoegen?

**Comment by jelmerderonde** [comment]
News: ook types calamiteiten, general, schedulechanges, ... opnemen?

**Comment by jelmerderonde** [comment]
See #95 for a PR proposing new enumerations
