### ISSUE TITLE
Mijn vragen die wellicht in handreiking kunnen

### ISSUE THREAD

**Issue by JanHendrikvanSchaik** [open-education-api/specification#93]
1. Hoe zie ik welke course welke periodes/weken wordt aangeboden?
    Met sinds krijg ik toch meer dan ik wil.
    Geeft me de cursussen in P2, geeft dan ook P3 en P4 cursussen..

2. Hoe worden de “components types” vastgesteld?
 

3. Komen er nog groepen in OOAPI?

**Comment by jelmerderonde** [comment]
Wellicht een until query parameter toevoegen op /academic-sessions ?

**Comment by jelmerderonde** [comment]
Deze punten zijn verwerkt.
